version: 0.2
phases:
  pre_build:
    commands:
      - echo installing dependencies...
  build:
    commands:
      # run build script
      - echo Build started on `date`
      - echo Building React Application...

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - "**/*"
  name: My-App
  discard-paths: no
